# Generated by Django 3.1.1 on 2020-09-04 15:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200904_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
